### ISSUE TITLE
Issue 1: User can search player based on Name

### ISSUE THREAD

**Issue by Boyul-Kim** [Boyul-Kim/ajax-project#1]
📐 Plan
Create the homepage and profile page so that when user enters player's name, the profile page will populate with name

🖼️ Wireframe

![image](https://user-images.githubusercontent.com/35949989/98724512-bbc80f00-2348-11eb-8265-5e6a74ddb760.png)

## ✅ Task List

- [x] Create homepage
- [x] Create player profile page
- [x] Manipulate DOM to search player based on name from homepage
- [x] If player is real, populate player profile page with projected stats from api
