### ISSUE TITLE
Issue 2: User can search based on players based on statistical categories

### ISSUE THREAD

**Issue by Boyul-Kim** [Boyul-Kim/ajax-project#2]
📐 Plan
User should be able to see the past 5 years of the player and also the projected stats based on the averages of the players

🖼️ Wireframe
![image](https://user-images.githubusercontent.com/35949989/98754208-095d6f80-237b-11eb-8bff-3d817db521ff.png)

## ✅ Task List

- [x] style the page
- [x] create a new XMLHttpRequest to query all the players from data
- [x] inside the function, return the past 5 years of the averages of the selected player
- [x] return trends from past 5 years
- [x] return projected stats based on past 5 years
