### ISSUE TITLE
Issue 3: User can add a player into their draft list

### ISSUE THREAD

**Issue by Boyul-Kim** [Boyul-Kim/ajax-project#3]
📐 Plan
create the draft list page and add DOM manipulation

🖼️ Wireframe
![image](https://user-images.githubusercontent.com/35949989/98852215-31e17a00-240c-11eb-9700-45c8817b77b9.png)

## ✅ Task List

- [x] create draft list page skeleton
- [x] style draft list page
- [x] create the header links
- [x] dom manipulation from profile page to add player to draft list
