### ISSUE TITLE
Issue 4: User can view draft projections

### ISSUE THREAD

**Issue by Boyul-Kim** [Boyul-Kim/ajax-project#4]
📐 Plan
Populate the page with projected draft list

**🖼️ Wireframe**
![image](https://user-images.githubusercontent.com/35949989/98986230-7a1a9e00-24d9-11eb-9bb2-b07a14a37f9d.png)

## ✅ Task List

- [x] create page skeleton for draft projection
- [x] style the page
- [x] add DOM manipulation that will  trigger the API call
- [x] populate the page with the draft list
